# -*- coding: utf-8 -*-
__author__ = 'dhernand'

CONST_GNSS_3D_CAPTURE_NAME = "GNSS3DCapture"
CONST_GNSS_3D_CAPTURE_WINDOW_TITLE = "GNSS 3D Capture"
CONST_GNSS_3D_CAPTURE_SETTINGS_FILE_NAME = "GNSS3DCapturePlugin.ini"
CONST_GNSS_3D_CAPTURE_COMBOBOX_NO_SELECT_OPTION = " ... "
CONST_GNSS_3D_CAPTURE_GEOIDS_RELATIVE_PATH = "/share/proj"
CONST_GNSS_3D_CAPTURE_GEOIDS_FILE_EXTENSION = ".gtx"
CONST_GNSS_3D_CAPTURE_GEOIDS_FILTER_1 = "*.gtx"
CONST_GNSS_3D_CAPTURE_GEOIDS_NO_VALUE = -9999

CONST_GNSS_3D_CAPTURE_SAVE_POINT_WINDOW_TITLE = "GNSSS 3D Capture - Save Point"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_NO_POINT_NUMBER = -1
CONST_GNSS_3D_CAPTURE_SAVE_POINT_FIRST_POINT_NUMBER = 1
CONST_GNSS_3D_CAPTURE_SAVE_POINT_POINT_NUMBER_INCREMENT = 1
CONST_GNSS_3D_CAPTURE_SAVE_POINT_POINT_NUMBER_MINIMUM_VALUE = 1
CONST_GNSS_3D_CAPTURE_SAVE_POINT_POINT_NUMBER_MAXIMUM_VALUE = 100000
CONST_GNSS_3D_CAPTURE_SAVE_POINT_ANTENNA_HEIGHT_DEFAULT_VALUE = 0.0
CONST_GNSS_3D_CAPTURE_SAVE_POINT_ANTENNA_HEIGHT_MINIMUM_VALUE = 0.0
CONST_GNSS_3D_CAPTURE_SAVE_POINT_ANTENNA_HEIGHT_MAXIMUM_VALUE = 50.0
CONST_GNSS_3D_CAPTURE_SAVE_POINT_ANTENNA_HEIGHT_PRECISION = "{:.4f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_LONGITUDE_PRECISION = "{:.10f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_LATITUDE_PRECISION = "{:.10f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_EASTING_PRECISION = "{:.4f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_NORTHING_PRECISION = "{:.4f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_HEIGHT_PRECISION = "{:.4f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_GEOID_HEIGHT_PRECISION = "{:.4f}"
CONST_GNSS_3D_CAPTURE_SAVE_POINT_HEIGHT_FROM_GEOID_PRECISION = "{:.4f}"

CONST_GNSS_3D_CAPTURE_EPSG_CODE_GPS = 4326

CONST_GNSS_3D_CAPTURE_QML_TEMPLATES_FOLDER = "templates"
CONST_GNSS_3D_CAPTURE_QML_TEMPLATES_FOLDER_QML_POINT_NAME_Z = "Point_Name_Z.qml"
CONST_GNSS_3D_CAPTURE_QML_TEMPLATES_FOLDER_QML_POINT_NUMBER_Z = "Point_Number_Z.qml"
CONST_GNSS_3D_CAPTURE_QML_TEMPLATES_FOLDER_QML_POINT_Z = "Point_Z.qml"